### ISSUE TITLE
Do not throw inside of the append/prepend/prettydate methods

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-utilities#101]
By definition, all functions should have no side effects. It means that we should never throw.

## Acceptance criteria

- [ ] do not throw inside of the `append/prepend/methods`
- [ ]  append/prepend return the collection instead of throwing
- [ ] prettydate returns an empty string instead of throwing

**Comment by inikonorov** [comment]
done!

https://github.com/buxlabs/pure-utilities/pull/103

**Comment by emilos** [comment]
@inikonorov thanks!
