### ISSUE TITLE
Add a new `comma` method

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-utilities#68]
It should join an array elements with comma **,** separator. The second parameter should be spacing (default set to 0)

**Comment by emilos** [comment]
## Acceptance criteria

- [ ] `comma` method in `array.js`
- [ ] has two params, `array`, `spacing`, spacing defaults to 0
- [ ] spacing is a count of spaces after the comma character
- [ ] works for arrays
- [ ] tests
- [ ] docs
- [ ] examples

**Comment by inikonorov** [comment]
https://github.com/buxlabs/pure-utilities/pull/83

**Comment by emilos** [comment]
@inikonorov thanks x2!
