### ISSUE TITLE
New `occurences` method

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-utilities#70]
## Acceptance criteria
- [ ] `occurences` method in `collection.js`
- [ ] works for arrays (e.g. `occurences(["foo", "foo", "bar"], "foo")` returns 2)
- [ ] works for strings (e.g. `occurences("foo foo bar", "foo")` returns 2)
- [ ] tests
- [ ] docs
- [ ] examples

**Comment by inikonorov** [comment]
how this method must work with strings? can I consider that repeated substrings always separated by space?

**Comment by emilos** [comment]
@inikonorov that should be good enough for start, there's always room for improvement in the future if needed

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/85

**Comment by emilos** [comment]
@inikonorov thanks for all of the help! I've released it as `v1.1.16`
