### ISSUE TITLE
New helpers for date objects

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-utilities#77]
hours => returns the hour part from the date
minutes => returns the minutes from the date
seconds => returns the seconds from the date

**Comment by emilos** [comment]
## Acceptance criteria

- [ ] new `hours` method
- [ ] new `minutes` method
- [ ] new `seconds` method
- [ ] add docs
- [ ] add examples

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/87
