### ISSUE TITLE
Date format method - missing 0

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-utilities#78]
When the day number is smaller than 10, the `format` method should prepend the number with the zero

**Comment by emilos** [comment]
https://buxlabs.pl/en/tools/js/pure-utilities/repl#format

## Acceptance criteria
- [ ] `format` method prepends 0 to a day when day < 10
- [ ] add an example to the documentation

**Comment by inikonorov** [comment]
done!

https://github.com/buxlabs/pure-utilities/pull/86
