### ISSUE TITLE
Extend the `compact` method to accept a `strict` flag

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-utilities#79]
We can add a new helper which may be helpful in some situations.
For example we sometimes  do some operations on collections and later when we want to filter null values we need to use e.g. `filter.Boolean()`

compactmap should make transformations on elements but omits undefined and null values.
We can add also a strict flag or something similar to remove all falsy values

https://www.avanderlee.com/swift/compactmap-flatmap-differences-explained/
https://www.npmjs.com/package/compact-map

**Comment by emilos** [comment]
I'd suggest to add a second param called `strict` (defaults to true) to the `compact` method. If it's set to false, only filter `null` and `undefined`.

## Acceptance criteria

- [ ] add `strict` flag as a second parameter to the `compact` method
- [ ] `strict` is set to `true` by default
- [ ] filter out only `null` and `undefined` if `strict` is set to false
- [ ] update examples
- [ ] update documentation

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/82

**Comment by emilos** [comment]
@inikonorov thanks x3!  I've released the changes as `v1.1.15`
