### ISSUE TITLE
prettysize

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-utilities#80]
Sometimes we need to define the size of file in bytes, but it is hard to read how many kilobytes or megabytes is has the the file without using calculators or comments.
```js
 // max file size is 400 kB
 const MAX_FILE_SIZE = 409600
```

```js
 const MAX_FILE_SIZE = prettysize('400KB')
```

So we could pass  to the method string with specific unit for example '10KB' and it would be converted to bytes.

Maybe the better idea is passing to the method a configuration object.

**Comment by inikonorov** [comment]
where this method should located?

**Comment by emilos** [comment]
I'd add it to the `string.js` file as a method called `bytes` which takes in a string and returns a number

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/81
