### ISSUE TITLE
partition method

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-utilities#89]
## Acceptance criteria

- [ ] add `partition` method to `array.js`
- [ ] add tests
- [ ] add docs
- [ ] add examples
- [ ] method is side effect free (e.g. cannot throw)

## Useful links

https://lodash.com/docs/4.17.15#partition
https://stackoverflow.com/questions/11345296/partitioning-in-javascript

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/98

**Comment by emilos** [comment]
@inikonorov Thanks a lot again!
