### ISSUE TITLE
make `deepclone` pure

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-utilities#90]
## Context

In the README, we're stating that the methods are side effect free. Unfortunately it's not true in all of the cases yet.

```js
function deepclone (object) {
  return JSON.parse(JSON.stringify(object))
}
```

`deepclone` fn would throw if you'd pass `undefined` or when the parsed object has circular references.

## Acceptance criteria

- [ ] ensure deepclone does not throw
- [ ] add more tests

We probably need to add a default:

`function deepclone (object = {}) {}`

and wrap the fn body with try catch. The simplest thing to do is probably just return an empty object if there's an exception.

**Comment by inikonorov** [comment]
done! (at least so I think :smile: )
https://github.com/buxlabs/pure-utilities/pull/99

**Comment by emilos** [comment]
@inikonorov thanks!
