### ISSUE TITLE
Split functions into directories and separate files

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-utilities#92]
## Story

As a developer, I'd like to import a function per file so that the bundler I use has less work to do.

## Acceptance criteria

- [ ] create directories per type (array, string, collection etc.)
- [ ] create a file per function (e.g. deepclone, capitalize etc. are in separate files)
- [ ] create an index file (array/index.js) that requires all deps from given dir and exports them
- [ ] tests should work as they do now

**Comment by inikonorov** [comment]
Hi! Is it okay? 
https://github.com/buxlabs/pure-utilities/pull/100

If I did what you need, so I'll update this PR by adding another functions :)

**Comment by emilos** [comment]
@inikonorov that's correct!

**Comment by inikonorov** [comment]
in 'string' methods there is 'index' method - i can't create file with this name, because the main file of folder already has the same name. what should I do?

**Comment by emilos** [comment]
good question. Maybe put it inside the `index.js` file that imports other files as a function at the top

**Comment by inikonorov** [comment]
okay

**Comment by inikonorov** [comment]
done!
https://github.com/buxlabs/pure-utilities/pull/100

**Comment by emilos** [comment]
@inikonorov thanks so much for your time!
